// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    //'aws_app_analytics': 'enable',
    /*'aws_cognito_identity_pool_id': 'us-east-1:dea427db-6085-4d69-be53-51a5834cbe32', //'us-east-1:88897bd1-7853-401d-a011-9ea3368dcc99',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'asteria-hosting-mobilehub-1870751388',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1cajqzc7s8oa.cloudfront.net',
    'aws_mobile_analytics_app_id': 'a3d0c5892ec2467b91333774a84577a8',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '31368928-fe34-4593-9d53-fd58d9efc138',
    'aws_project_name': 'Asteria-2019-07-31-20-38-55',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'asteria-mobilehub-1870751388',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id':'us-east-1_hfPpEAFz0',// 'us-east-1_mFXpnfQn1',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '498gr1ngs0lcttv4qfmmci74qp',// '3q1p3t37nrjleog65pbon3qpq0', 
    */
   
    'aws_cognito_identity_pool_id': 'us-east-1:88897bd1-7853-401d-a011-9ea3368dcc99',
    'aws_cognito_region': 'us-east-1',
     'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_id': 'us-east-1_mFXpnfQn1',
    'aws_user_pools_web_client_id': '3q1p3t37nrjleog65pbon3qpq0'
}

export default awsmobile;
